require 'erb'

# Generated by Linecook, do not edit.
module Linebook
  module Shell
    module Posix
      def quote(arg)
        "\"#{arg}\""
      end
      
      def blank?(obj)
        obj.nil? || obj.to_s.strip.empty?
      end
      
      def nest_opts(opts, default={})
        opts = default if opts.nil? || opts == true
        opts && block_given? ? yield(opts) : opts
      end
      
      # Adds a check that ensures the last exit status is as indicated. Note that no
      # check will be added unless check_status_function is added beforehand.
      # 
      def check_status(status=0)
        @check_status ||= false
        #  <% if @check_status %>
        #  check_status <%= status %> $? $LINENO
        #  
        #  <% end %>
        if @check_status 
        _erbout.concat "check_status "; _erbout.concat(( status ).to_s); _erbout.concat " $? $LINENO\n"
        _erbout.concat "\n"
        end ;
        nil
      end
      
      def _check_status(*args, &block) # :nodoc:
        capture { check_status(*args, &block) }
      end
      
      # Adds the check status function.
      def check_status_function()
        @check_status = true
        #  check_status () { 
        #    if [ $1 -ne $2 ]
        #    then
        #      echo "[$2] $0:$3"
        #      exit $2
        #    fi
        #    return $1
        #  }
        #  
        _erbout.concat "check_status () { \n"
        _erbout.concat "  if [ $1 -ne $2 ]\n"
        _erbout.concat "  then\n"
        _erbout.concat "    echo \"[$2] $0:$3\"\n"
        _erbout.concat "    exit $2\n"
        _erbout.concat "  fi\n"
        _erbout.concat "  return $1\n"
        _erbout.concat "}\n"
        nil
      end
      
      def _check_status_function(*args, &block) # :nodoc:
        capture { check_status_function(*args, &block) }
      end
      
      # Execute a command and check the output status.
      def cmd(cmd, *args)
        args.compact!
        args = args.collect! {|arg| arg[0] == ?- ? arg : quote(arg) }
        args.unshift(cmd)
        #  <%= args.join(' ') %>
        #  
        #  <% check_status %>
        _erbout.concat(( args.join(' ') ).to_s)
        _erbout.concat "\n"
        check_status ;
        nil
      end
      
      def _cmd(*args, &block) # :nodoc:
        capture { cmd(*args, &block) }
      end
      
      # Writes a comment
      def comment(str)
        #  # <%= str %>
        #  
        _erbout.concat "# "; _erbout.concat(( str ).to_s); _erbout.concat "\n"
        nil
      end
      
      def _comment(*args, &block) # :nodoc:
        capture { comment(*args, &block) }
      end
      
      # Exports a list of variables.
      def export(env=[])
        #  <% env.to_a.each do |(key, value)| %>
        #  export <%= key %>=<%= value %>
        #  <% end %><% if block_given? %>
        #  <% indent { yield } %>
        #  <% unset(*env.collect {|(k,v)| k }) %>
        #  <% end %>
        #  
        #  
        env.to_a.each do |(key, value)| 
        _erbout.concat "export "; _erbout.concat(( key ).to_s); _erbout.concat "="; _erbout.concat(( value ).to_s); _erbout.concat "\n"
        end ;  if block_given? 
        indent { yield } 
        unset(*env.collect {|(k,v)| k }) 
        end 
        _erbout.concat "\n"
        nil
      end
      
      def _export(*args, &block) # :nodoc:
        capture { export(*args, &block) }
      end
      
      # Makes a heredoc statement surrounding the contents of the block.  Options:
      # 
      #   delimiter   the delimiter used, by default HEREDOC_n where n increments
      #   indent      add '-' before the delimiter
      #   quote       quotes the delimiter
      # 
      def heredoc(options={})
        delimiter = options[:delimiter] || begin
          @heredoc_count ||= -1
          "HEREDOC_#{@heredoc_count += 1}"
        end
        #  <<<%= options[:indent] ? '-' : ' '%><%= options[:quote] ? "\"#{delimiter}\"" : delimiter %>
        #  <% yield %>
        #  <%= delimiter %>
        #  
        #  
        _erbout.concat "<<"; _erbout.concat(( options[:indent] ? '-' : ' ').to_s); _erbout.concat(( options[:quote] ? "\"#{delimiter}\"" : delimiter ).to_s); _erbout.concat "\n"
        yield 
        _erbout.concat(( delimiter ).to_s)
        _erbout.concat "\n"
        nil
      end
      
      def _heredoc(*args, &block) # :nodoc:
        capture { heredoc(*args, &block) }
      end
      
      def not_if(cmd, &block)
        only_if("! #{cmd}", &block)
        nil
      end
      
      def _not_if(*args, &block) # :nodoc:
        capture { not_if(*args, &block) }
      end
      
      def only_if(cmd)
        #  if <%= cmd %>
        #  then
        #  <% indent { yield } %>
        #  fi
        #  
        #  
        _erbout.concat "if "; _erbout.concat(( cmd ).to_s); _erbout.concat "\n"
        _erbout.concat "then\n"
        indent { yield } 
        _erbout.concat "fi\n"
        _erbout.concat "\n"
        nil
      end
      
      def _only_if(*args, &block) # :nodoc:
        capture { only_if(*args, &block) }
      end
      
      # Sets the options to on (true) or off (false) as specified.
      def set_options(options)
        #  <% options.keys.sort_by {|opt| opt.to_s }.each do |opt| %>
        #  set <%= options[opt] ? '-' : '+' %>o <%= opt %>
        #  <% end %>
        options.keys.sort_by {|opt| opt.to_s }.each do |opt| 
        _erbout.concat "set "; _erbout.concat(( options[opt] ? '-' : '+' ).to_s); _erbout.concat "o "; _erbout.concat(( opt ).to_s); _erbout.concat "\n"
        end ;
        nil
      end
      
      def _set_options(*args, &block) # :nodoc:
        capture { set_options(*args, &block) }
      end
      
      # Unsets a list of variables.
      def unset(*keys)
        #  <% keys.each do |key| %>
        #  unset <%= key %>
        #  <% end %>
        keys.each do |key| 
        _erbout.concat "unset "; _erbout.concat(( key ).to_s); _erbout.concat "\n"
        end ;
        nil
      end
      
      def _unset(*args, &block) # :nodoc:
        capture { unset(*args, &block) }
      end
    end
  end
end
