require 'erb'

# Generated by Linecook, do not edit.
module Linebook
  module Shell
    module Posix
      # Encloses the arg in quotes ("").
      def quote(arg)
        quoted?(arg) || !quote?(arg) ? arg : "\"#{arg}\""
      end
      
      # Returns true if the arg is not an option, and is not already quoted (either
      # by quotes or apostrophes).  The intention is to check whether an arg
      # _should_ be quoted.
      def quote?(arg)
        arg[0] == ?- || quoted?(arg) ? false : true
      end
      
      # Returns true if the arg is quoted (either by quotes or apostrophes).
      def quoted?(arg)
        arg =~ /\A".*"\z/ || arg =~ /\A'.*'\z/ ? true : false
      end
      
      # Returns true if the obj converts to a string which is whitespace or empty.
      def blank?(obj)
        # shortcut for nil...
        obj.nil? || obj.to_s.strip.empty?
      end
      
      # The prefix added to all execute calls.
      attr_accessor :execute_prefix
      
      # Sets execute_prefix for the duration of a block.
      def with_execute_prefix(prefix)
        current = execute_prefix
        begin
          self.execute_prefix = prefix
          yield
        ensure
          self.execute_prefix = current
        end
      end
      
      # The suffix added to all execute calls.
      attr_accessor :execute_suffix
      
      # Sets execute_suffix for the duration of a block.
      def with_execute_suffix(suffix)
        current = execute_suffix
        begin
          self.execute_suffix = suffix
          yield
        ensure
          self.execute_suffix = current
        end
      end
      
      # Formats a hash key-value string into command line options using the
      # following heuristics:
      #
      # * Prepend '--' to mulit-char keys and '-' to single-char keys (unless
      #   they already start with '-').
      # * For true values return the '--key'
      # * For false/nil values return nothing
      # * For all other values, quote (unless already quoted) and return '--key
      #  "value"'
      #
      # In addition, key formatting is performed on non-string keys (typically
      # symbols) such that underscores are converted to dashes, ie :some_key =>
      # 'some-key'.
      def format_execute_options(opts)
        options = []
        
        opts.each do |(key, value)|
          unless key.kind_of?(String)
            key = key.to_s.gsub('_', '-')
          end
          
          unless key[0] == ?-
            prefix = key.length == 1 ? '-' : '--'
            key = "#{prefix}#{key}"
          end
          
          case value
          when true
            options << key
          when false, nil
            next
          else
            options << "#{key} #{quote(value.to_s)}"
          end
        end
        
        options.sort
      end
      
      # Adds a check that ensures the last exit status is as indicated. Note that no
      # check will be added unless check_status_function is added beforehand.
      def check_status(expect_status=0, fail_status='$?')
        @check_status ||= false
        
        #  <% if @check_status %>
        #  check_status <%= expect_status %> $? <%= fail_status %> $LINENO
        #  
        #  <% end %>
        if @check_status 
        _erbout.concat "check_status "; _erbout.concat(( expect_status ).to_s); _erbout.concat " $? "; _erbout.concat(( fail_status ).to_s); _erbout.concat " $LINENO\n"
        _erbout.concat "\n"
        end ;
        self
      end
      
      def _check_status(*args, &block) # :nodoc:
        capture { check_status(*args, &block) }
      end
      
      # Adds the check status function.
      def check_status_function()
        @check_status = true
        #  check_status () { if [ $2 -ne $1 ]; then echo "[$2] $0:${4:-?}"; exit $3; else return $2; fi }
        #  
        _erbout.concat "check_status () { if [ $2 -ne $1 ]; then echo \"[$2] $0:${4:-?}\"; exit $3; else return $2; fi }\n"
        self
      end
      
      def _check_status_function(*args, &block) # :nodoc:
        capture { check_status_function(*args, &block) }
      end
      
      # Execute a command and check the output status.  Arguments are quoted with ""
      # unless they begin with '-' or are already quoted.
      def cmd(command, *args)
        args.compact!
        args.collect! {|arg| quote(arg) }
        args.unshift(command)
        #  <%= args.join(' ') %>
        #  
        #  <% check_status %>
        _erbout.concat(( args.join(' ') ).to_s)
        _erbout.concat "\n"
        check_status ;
        self
      end
      
      def _cmd(*args, &block) # :nodoc:
        capture { cmd(*args, &block) }
      end
      
      # Writes a comment
      def comment(str)
        #  # <%= str %>
        #  
        _erbout.concat "# "; _erbout.concat(( str ).to_s); _erbout.concat "\n"
        self
      end
      
      def _comment(*args, &block) # :nodoc:
        capture { comment(*args, &block) }
      end
      
      # Execute a command and check the output status. Arguments are quoted with ""
      # unless they begin with '-' or are already quoted. If the last arg is a hash,
      # then it will be formatted into options and prepended to args.
      # 
      # Execute also allows a prefix/suffix to wrap the command and args. See
      # with_execute_prefix and with_execute_suffix.
      def execute(command, *args)
        opts = args.last.kind_of?(Hash) ? args.pop : {}
        args.compact!
        args.collect! {|arg| quote(arg) }
        
        args = format_execute_options(opts) + args
        args.unshift(command)
        #  <%= execute_prefix %><%= args.join(' ') %><%= execute_suffix %>
        #  
        #  <% check_status %>
        _erbout.concat(( execute_prefix ).to_s); _erbout.concat(( args.join(' ') ).to_s); _erbout.concat(( execute_suffix ).to_s)
        _erbout.concat "\n"
        check_status ;
        self
      end
      
      def _execute(*args, &block) # :nodoc:
        capture { execute(*args, &block) }
      end
      
      # Exports a list of variables.
      def export(env=[])
        #  <% env.to_a.each do |(key, value)| %>
        #  export <%= key %>=<%= value %>
        #  <% end %><% if block_given? %>
        #  <% indent { yield } %>
        #  <% unset(*env.collect {|(k,v)| k }) %>
        #  <% end %>
        #  
        #  
        env.to_a.each do |(key, value)| 
        _erbout.concat "export "; _erbout.concat(( key ).to_s); _erbout.concat "="; _erbout.concat(( value ).to_s); _erbout.concat "\n"
        end ;  if block_given? 
        indent { yield } 
        unset(*env.collect {|(k,v)| k }) 
        end 
        _erbout.concat "\n"
        self
      end
      
      def _export(*args, &block) # :nodoc:
        capture { export(*args, &block) }
      end
      
      # Makes a heredoc statement surrounding the contents of the block.  Options:
      # 
      #   delimiter   the delimiter used, by default HEREDOC_n where n increments
      #   outdent     add '-' before the delimiter
      #   quote       quotes the delimiter
      def heredoc(options={})
        delimiter = options[:delimiter] || begin
          @heredoc_count ||= -1
          "HEREDOC_#{@heredoc_count += 1}"
        end
        #  <<<%= options[:outdent] ? '-' : ' '%><%= options[:quote] ? "\"#{delimiter}\"" : delimiter %><% outdent(" # :#{delimiter}:") do %>
        #  <% yield %>
        #  <%= delimiter %><% end %>
        #  
        #  
        _erbout.concat "<<"; _erbout.concat(( options[:outdent] ? '-' : ' ').to_s); _erbout.concat(( options[:quote] ? "\"#{delimiter}\"" : delimiter ).to_s);  outdent(" # :#{delimiter}:") do ; _erbout.concat "\n"
        yield 
        _erbout.concat(( delimiter ).to_s);  end 
        _erbout.concat "\n"
        self
      end
      
      def _heredoc(*args, &block) # :nodoc:
        capture { heredoc(*args, &block) }
      end
      
      def not_if(cmd, &block)
        only_if("! #{cmd}", &block)
        self
      end
      
      def _not_if(*args, &block) # :nodoc:
        capture { not_if(*args, &block) }
      end
      
      def only_if(cmd)
        #  if <%= cmd %>
        #  then
        #  <% indent { yield } %>
        #  fi
        #  
        #  
        _erbout.concat "if "; _erbout.concat(( cmd ).to_s); _erbout.concat "\n"
        _erbout.concat "then\n"
        indent { yield } 
        _erbout.concat "fi\n"
        _erbout.concat "\n"
        self
      end
      
      def _only_if(*args, &block) # :nodoc:
        capture { only_if(*args, &block) }
      end
      
      # Sets the options to on (true) or off (false) as specified.
      def set_options(options)
        #  <% options.keys.sort_by {|opt| opt.to_s }.each do |opt| %>
        #  set <%= options[opt] ? '-' : '+' %>o <%= opt %>
        #  <% end %>
        options.keys.sort_by {|opt| opt.to_s }.each do |opt| 
        _erbout.concat "set "; _erbout.concat(( options[opt] ? '-' : '+' ).to_s); _erbout.concat "o "; _erbout.concat(( opt ).to_s); _erbout.concat "\n"
        end ;
        self
      end
      
      def _set_options(*args, &block) # :nodoc:
        capture { set_options(*args, &block) }
      end
      
      # Unsets a list of variables.
      def unset(*keys)
        #  <% keys.each do |key| %>
        #  unset <%= key %>
        #  <% end %>
        keys.each do |key| 
        _erbout.concat "unset "; _erbout.concat(( key ).to_s); _erbout.concat "\n"
        end ;
        self
      end
      
      def _unset(*args, &block) # :nodoc:
        capture { unset(*args, &block) }
      end
    end
  end
end
