#!/bin/sh

# Test Suite
MESSAGES=messages
RESULTS=results
START_TIME=$SECONDS

${0%/test_suite}/test_case_one 2>>"$MESSAGES" | tee -a "$RESULTS"
${0%/test_suite}/test_case_two 2>>"$MESSAGES" | tee -a "$RESULTS"

END_TIME=$SECONDS

echo
echo
cat "$MESSAGES"
echo "$(grep -c "\." "$RESULTS") pass, $(grep -c "F" "$RESULTS") fail ($(($END_TIME - $START_TIME))s elapsed)"
rm "$MESSAGES" "$RESULTS"
