#!/bin/sh
. ${0%/test_case_one}/test_helper

########################################################################
TEST_CASE=One
########################################################################

setup () {
  VAR=
}

teardown () {
  VAR=
}

test_one () {
  setup
  true
  assert_status_equal 0 $? $LINENO
  teardown
}

test_two () {
  setup
  true
  assert_status_equal 0 $? $LINENO
  teardown
}

test_three () {
  setup
  false
  assert_status_equal 0 $? $LINENO
  teardown
}

test_four () {
  setup
  true
  assert_status_equal 0 $? $LINENO
  teardown
}

test_five () {
  setup
  false
  assert_status_equal 0 $? $LINENO
  teardown
}

run_tests "$0"
