require 'erb'

# Generated by Linecook, do not edit.
module Linebook
  module Shell
    require 'linebook/shell/unix'
    include Unix
    
    def self.extended(base)
      base.attributes 'linebook/shell'
      
      if shell = base.attrs['linebook']['shell']
        base.helpers shell
      end
      
      if os = base.attrs['linebook']['os']
        base.helpers os
      end
      
      super
    end
    
    def guess_target_name(source_name)
      next_target_name File.join("#{target_name}.d", File.basename(source_name))
    end
    
    def log_dir
      '/var/log/linecook'
    end
    
    # Backup a file.
    def backup(path, options={})
      backup_path = "#{path}.bak"
      if options[:mv]
        mv_f path, backup_path
      else
        cp_f path, backup_path
      end
      
      chmod 644, backup_path
      nil
    end
    
    def _backup(*args, &block) # :nodoc:
      capture { backup(*args, &block) }
    end
    
    def directory(target, options={})
      not_if _directory?(target) do 
        mkdir_p target
      end 
      chmod options[:mode], target
      chown options[:user], options[:group], target
      nil
    end
    
    def _directory(*args, &block) # :nodoc:
      capture { directory(*args, &block) }
    end
    
    def execute(cmd)
      #  <%= cmd %>
      #  
      #  <% check_status %>
      #  
      _erbout.concat(( cmd ).to_s)
      _erbout.concat "\n"
      check_status
      nil
    end
    
    def _execute(*args, &block) # :nodoc:
      capture { execute(*args, &block) }
    end
    
    # Installs a file from the package.
    def file(file_name, target, options={})
      source = file_path(file_name, guess_target_name(target))
      install(source, target, options)
      nil
    end
    
    def _file(*args, &block) # :nodoc:
      capture { file(*args, &block) }
    end
    
    def group?(name)
      #  grep "^<%= name %>:" /etc/group
      _erbout.concat "grep \"^"; _erbout.concat(( name ).to_s); _erbout.concat ":\" /etc/group";
      nil
    end
    
    def _group?(*args, &block) # :nodoc:
      capture { group?(*args, &block) }
    end
    
    def group(name, options={})
      not_if _group?(name) do
        addgroup name
      end
      nil
    end
    
    def _group(*args, &block) # :nodoc:
      capture { group(*args, &block) }
    end
    
    # Installs a file
    def install(source, target, options={})
      nest_opts(options[:backup], :mv => true) do |opts|
        only_if _file?(target) do
          backup target, opts
        end
      end
      
      nest_opts(options[:directory]) do |opts|
        directory File.dirname(target), opts
      end
      
      cp source, target
      chmod options[:mode], target
      chown options[:user], options[:group], target
      nil
    end
    
    def _install(*args, &block) # :nodoc:
      capture { install(*args, &block) }
    end
    
    def package(name, version=nil)
      raise NotImplementedError
      nil
    end
    
    def _package(*args, &block) # :nodoc:
      capture { package(*args, &block) }
    end
    
    def recipe(recipe_name)
      target_name = File.join('recipes', recipe_name)
      runlist = target_path "runlist.log"
      recipe_path = @package.registry.has_key?(target_name) ? 
        target_path(target_name) : 
        self.recipe_path(recipe_name, target_name)
      
      not_if %{grep -xqs "#{recipe_name}" "#{runlist}"} do
        target.puts %{echo "#{recipe_name}" >> "#{runlist}"}
        target.puts %{"#{env_path}" - "#{shell_path}" "#{recipe_path}" $*}
        check_status
      end
      nil
    end
    
    def _recipe(*args, &block) # :nodoc:
      capture { recipe(*args, &block) }
    end
    
    # Installs a template from the package.
    def template(template_name, target, options={})
      locals = options[:locals] || {}
      source = template_path(template_name, guess_target_name(target), locals)
      install(source, target, options)
      nil
    end
    
    def _template(*args, &block) # :nodoc:
      capture { template(*args, &block) }
    end
    
    def user(name, options={})
      not_if _user?(name) do
        adduser name
      end
      nil
    end
    
    def _user(*args, &block) # :nodoc:
      capture { user(*args, &block) }
    end
  end
end
