require 'erb'

# Generated by Linecook, do not edit.
module Linebook
  module Os
    module Ubuntu
      require 'linebook/os/linux'
      include Linux
      
      # Installs a package using apt-get, by default with the options '-q -y'.
      def package(name, version=nil, options={})
        name = "#{name}=#{version}" unless blank?(version)
        execute "apt-get install", name, {:q => true, :y => true}.merge(options)
        self
      end
      
      def _package(*args, &block) # :nodoc:
        capture { package(*args, &block) }
      end
    end
  end
end
