require 'erb'

# Generated by Linecook, do not edit.
module Linebook
  module Os
    module Ubuntu
      def addgroup(name)
        cmd 'addgroup', name
        nil
      end
      
      def _addgroup(*args, &block) # :nodoc:
        capture { addgroup(*args, &block) }
      end
      
      def adduser(name)
        cmd 'adduser', name
        nil
      end
      
      def _adduser(*args, &block) # :nodoc:
        capture { adduser(*args, &block) }
      end
      
      def package(name, version=nil)
        #  apt-get -q -y install <%= name %><%= blank?(version) ? nil : "=#{version}" %>
        #  <%= check_status %>
        _erbout.concat "apt-get -q -y install "; _erbout.concat(( name ).to_s); _erbout.concat(( blank?(version) ? nil : "=#{version}" ).to_s); _erbout.concat "\n"
        _erbout.concat(( check_status ).to_s);
        nil
      end
      
      def _package(*args, &block) # :nodoc:
        capture { package(*args, &block) }
      end
    end
  end
end
