# Generated by Linecook

module Linebook
  module Os
    # Defines basic UNIX utilities, and UNIX-compliant functionality. See the
    # online {Open Group Specification of UNIX
    # }[http://pubs.opengroup.org/onlinepubs/000095399/toc.htm] and specifically
    # the {list of standard utilties
    # }[http://pubs.opengroup.org/onlinepubs/000095399/idx/utilities.html].
    module Unix
      require 'linebook/os/posix'
      include Posix
      
      
      # Perform a gsub using sed.  Intended for use in chains.
      def gsub(pattern, replacement, *args)
        unless args.last.kind_of?(Hash)
          args << {}
        end
        args.last[:e] = "s/#{pattern}/#{replacement}/g"
        sed(*args)
        chain_proxy
      end
      
      def _gsub(*args, &block) # :nodoc:
        str = capture_str { gsub(*args, &block) }
        str.strip!
        str
      end
      
      # Sets the system time.
      def set_date(time=Time.now) 
        #  date -u <%= time.dup.utc.strftime("%m%d%H%M%Y.%S") %>
        #  <% check_status %>
        write "date -u "; write(( time.dup.utc.strftime("%m%d%H%M%Y.%S") ).to_s); write "\n"
        check_status 
        chain_proxy
      end
      
      def _set_date(*args, &block) # :nodoc:
        str = capture_str { set_date(*args, &block) }
        str.strip!
        str
      end
    end
  end
end
